name: Develop Pipeline

#Permission minimale
permissions:
  contents: read

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  NODE_VERSION: '20' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Installation de npm
        run: sudo apt-get install npm

      - name: Installation de pnpm
        run: sudo npm install -g pnpm
          
      - name: Installation des dépendances
        run: pnpm install

      - name: Installation de Angular/CLI
        run: pnpm install -g @angular/cli

      - name: lancement des tests
        run: ng test
